### ISSUE TITLE
Retain MQTT

### ISSUE THREAD

**Issue by Drealine** [jnsbyr/esp8266-intexsbh20#11]
Add retain option to maintain MQTT value when is using with Home Assistant

**Comment by Drealine** [comment]
I will create a new PR attached to this issue

**Comment by jnsbyr** [comment]
@Drealine 

Your change affects retaining and forced publishing at the same time. While I understand that in some scenarios retaining of MQTT messages is desired, forced publishing will only create more WiFi traffic.

Commit 93441a1 adds a new config value to enable retaining if needed and reverts all changes related to forced publishing.
