### ISSUE TITLE
error parsing config file: NoMemory

### ISSUE THREAD

**Issue by vrsho** [jnsbyr/esp8266-intexsbh20#18]
HI,

when i enter mqtt user and password in config file it cannot be read cause of insufficient memory. In console i receive this error: error parsing config file: NoMemory.

**Comment by vrsho** [comment]
Okay i figured it out. 

CONFIG_BUFFER_SIZE need to be increased.

**Comment by jnsbyr** [comment]
Good choice. This is a problem several users stumbled over after MQTT authentication was introduced without changing the buffer size. There is a merge request waiting (#17) that will fix this.

**Comment by jnsbyr** [comment]
fix, use https://github.com/jnsbyr/esp8266-intexsbh20/releases/tag/1.0.2.1
