### ISSUE TITLE
Has anyone studied the possibility of connecting a solar panel ?

### ISSUE THREAD

**Issue by louis49** [jnsbyr/esp8266-intexsbh20#20]
I discovered that this spa consumes a lot of electricity and I would like to be able to partly heat the water with solar panels by adding them between the SPA and the pump (and thus use the pump through the solar panels).
Some questions :

- Do you think the pump can hold the style of assembling? 
- Could a solenoid valve be added without consuming too much electricity (on 5v pin) and then allow the temperature to be limited to the maximum temperature of the SPA? 
- Can solar panels allow to go near to the maximum temperature of the SPA? What gain is possible ?

Thank you

**Comment by jnsbyr** [comment]
I assume you are talking about thermal panels and not electric panels. 

> Do you think the pump can hold the style of assembling?

The pump is the weakest component of the SBH in respect to its power and power consumption. Adding thermal panels will probably reduce the water throughput further. The flow resistance might be found in the specs of the panels. If the smallest diameter of the pipe through the panels is not significantly smaller than that of the SBH you might get lucky but you will probably need an additional pump.

> Could a solenoid valve be added without consuming too much electricity (on 5v pin) and then allow the temperature to be limited to the maximum temperature of the SPA?

There is not much spare room inside the SBH pump case and it is even harder to add anything in a electrically safe way. But if you attach the solenoid in place of the electric heater you should have ample power at 230VAC. It is not a good idea to use a CPU pin from the mainboard directly. You would also need to modify the pipes of the SBH, probably on their way between the case and the pool. It should be easier to attach the valve outside the case.

> Can solar panels allow to go near to the maximum temperature of the SPA? What gain is possible ?

Thermal panels can produce very high temperatures, even above 100 °C. If you have very powerful panels I would not trust the temperature regulator of the SBH to do this safely. If you have panels with a power similar to the build in electric heater of the SBH it should not be a problem. 

Note that I did not try this myself. Maybe someone with more experience can add a comment.
