### ISSUE TITLE
MQTT Server/Broker IP

### ISSUE THREAD

**Issue by Telo87** [jnsbyr/esp8266-intexsbh20#24]
Is ist possible to enter the IP of the MQTT-Server in the config.json?
Or what do I have to change to make it work?

**Comment by jnsbyr** [comment]
I would assume yes, but documentation of the underlying API [PubSubClient::setServer](https://pubsubclient.knolleary.net/api#setServer) is a little unspecific in this regard, just saying "the address of the server".

This is an overloaded function call so it would be possible to switch to the IP specific function variant if necessary, but it is probably much easier to just give it a try. A web searched regarding this question indicates that it will work (e.g. http://www.steves-internet-guide.com/using-arduino-pubsub-mqtt-client/).

In the config file it would look like this:
`"mqttServer":     "1.2.3.4",`

**Comment by Telo87** [comment]
Thanks for the quick response.
I use iobroker with the mqtt broker as server. My other mqtt clients all work, but the intex project just won't work. Unfortunately I have no idea if the problem is with the ESP, the wiring or the software.
The ESP is connected to the WLAN and can also be pinged.

Below are some pictures of my configuration:
config.json
![grafik](https://user-images.githubusercontent.com/95292648/215572044-0023a6b4-caaa-4a02-bd30-cc080a08baac.png)

iobroker Server
![grafik](https://user-images.githubusercontent.com/95292648/215572427-15e37072-904b-4a8d-9cbd-0a73aaa91507.png)

iobroker Client
![grafik](https://user-images.githubusercontent.com/95292648/215572704-309a9c7e-593a-4be4-8090-65cdb07d330b.png)


Do the data points have to be added manually at iobroker?

Many Thanks

**Comment by jnsbyr** [comment]
I have no experience with the iobroker myself. Maybe someone else can provide more specific help. Here are some general ideas:

- check that the ESP is connected to the iobroker on port 1883 - it will try to connect immediately after boot. I would assume that the iobroker has a status display for this. Even if not, your OS should be able to tell you. On Windows and older Linux use "netstat -tn", on newer Linux use "ss". The IP of the ESP and the port 1883 should be shown as "connected". If it is not, there might be something wrong on the ESP side. Connect a TTL/USB adapter to the serial TX of the EPS and listen with a serial monitor (PuTTY, Arduino IDE) at 74880 Baud. If you are lucky you might get some specific error message.
- PubSubClient only supports MQTT version 3.1 and 3.1.1 (see https://github.com/knolleary/pubsubclient)
- This is a custom device so the iobroker will probably not be able to do an auto configuration. You might need to add the MQTT topics listed in the [README.md](https://github.com/jnsbyr/esp8266-intexsbh20#mqtt) manually. The ESP will start publishing the MQTT topics immediately after connect. If the TCP connection gets established you can listen in with a network tool like tcpdump or Wireshark.
