### ISSUE TITLE
ESP Home installation failed.

### ISSUE THREAD

**Issue by RianFlow** [jnsbyr/esp8266-intexsbh20#27]
Hello. When installing on the wemos d1 mini, I keep getting errors. I've attached the log. maybe you can do something with it. Would appreciate any help.
[logs_esphome-web-819576_run.txt](https://github.com/jnsbyr/esp8266-intexsbh20/files/11583883/logs_esphome-web-819576_run.txt)

ESPHome 2023.5.4
INFO Reading configuration /config/esphome/esphome-web-819576.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-819576 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 160MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/SBH20IO.cpp.o
Compiling /data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/SBHClimate.cpp.o
src/esphome/components/intexsbh20/SBH20IO.cpp:1:1: error: expected unqualified-id before '.' token
    1 | ../../../SBH20IO.cpp
      | ^
Compiling /data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/intexsbh20.cpp.o
Compiling /data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/md5/md5.cpp.o
*** [/data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/SBH20IO.cpp.o] Error 1
In file included from src/esphome/components/intexsbh20/intexsbh20.h:6,
                 from src/esphome/components/intexsbh20/intexsbh20.cpp:1:
src/esphome/components/intexsbh20/SBH20IO.h:1:1: error: expected unqualified-id before '.' token
    1 | ../../../SBH20IO.h
      | ^
In file included from src/esphome/components/intexsbh20/intexsbh20.cpp:2:
src/esphome/components/intexsbh20/SBHSwitch.h:10:77: error: 'IntexSBH20' was not declared in this scope
   10 | class SBHSwitch : public esphome::switch_::Switch, public esphome::Parented<IntexSBH20>
      |                                                                             ^~~~~~~~~~
src/esphome/components/intexsbh20/SBHSwitch.h:10:87: error: template argument 1 is invalid
   10 | class SBHSwitch : public esphome::switch_::Switch, public esphome::Parented<IntexSBH20>
      |                                                                                       ^
src/esphome/components/intexsbh20/SBHSwitch.h: In member function 'virtual void esphome::sbh20::SBHSwitch::write_state(bool)':
src/esphome/components/intexsbh20/SBHSwitch.h:27:4: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   27 |    get_parent()->sbh()->setBubbleOn(state);
      |    ^~~~~~~~~~
      |    get_name
src/esphome/components/intexsbh20/SBHSwitch.h:31:4: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   31 |    get_parent()->sbh()->setFilterOn(state);
      |    ^~~~~~~~~~
      |    get_name
src/esphome/components/intexsbh20/SBHSwitch.h:35:4: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   35 |    get_parent()->sbh()->setPowerOn(state);
      |    ^~~~~~~~~~
      |    get_name
src/esphome/components/intexsbh20/SBHSwitch.h:43:7: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   43 |   if (get_parent()->sbh()->isOnline())
      |       ^~~~~~~~~~
      |       get_name
In file included from src/esphome/components/intexsbh20/intexsbh20.h:6,
                 from src/esphome/components/intexsbh20/SBHClimate.h:4,
                 from src/esphome/components/intexsbh20/SBHClimate.cpp:1:
src/esphome/components/intexsbh20/SBH20IO.h:1:1: error: expected unqualified-id before '.' token
    1 | ../../../SBH20IO.h
      | ^
In file included from src/esphome/components/intexsbh20/SBHClimate.cpp:1:
src/esphome/components/intexsbh20/SBHClimate.h:9:95: error: 'IntexSBH20' is not a member of 'esphome::sbh20'
    9 | class SBHClimate : public esphome::climate::Climate, public esphome::Parented<esphome::sbh20::IntexSBH20>
      |                                                                                               ^~~~~~~~~~
src/esphome/components/intexsbh20/SBHClimate.h:9:105: error: template argument 1 is invalid
    9 | class SBHClimate : public esphome::climate::Climate, public esphome::Parented<esphome::sbh20::IntexSBH20>
      |                                                                                                         ^
src/esphome/components/intexsbh20/SBHClimate.cpp: In member function 'void esphome::sbh20::SBHClimate::update()':
src/esphome/components/intexsbh20/SBHClimate.cpp:8:2: error: 'SBH20IO' was not declared in this scope
    8 |  SBH20IO* sbh = get_parent()->sbh();
      |  ^~~~~~~
src/esphome/components/intexsbh20/SBHClimate.cpp:8:11: error: 'sbh' was not declared in this scope; did you mean 'sbh20'?
    8 |  SBH20IO* sbh = get_parent()->sbh();
      |           ^~~
      |           sbh20
src/esphome/components/intexsbh20/SBHClimate.cpp:8:17: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
    8 |  SBH20IO* sbh = get_parent()->sbh();
      |                 ^~~~~~~~~~
      |                 get_name
src/esphome/components/intexsbh20/SBHClimate.cpp:30:44: error: 'SBH20IO' is not a class, namespace, or enumeration
   30 |  this->target_temperature = (targetTemp != SBH20IO::UNDEF::USHORT) ? targetTemp : SBH20IO::WATER_TEMP::SET_MIN;
      |                                            ^~~~~~~
src/esphome/components/intexsbh20/SBHClimate.cpp:30:83: error: 'SBH20IO' is not a class, namespace, or enumeration
   30 |  this->target_temperature = (targetTemp != SBH20IO::UNDEF::USHORT) ? targetTemp : SBH20IO::WATER_TEMP::SET_MIN;
      |                                                                                   ^~~~~~~
src/esphome/components/intexsbh20/SBHClimate.cpp:32:20: error: 'SBH20IO' is not a class, namespace, or enumeration
   32 |  if (targetTemp == SBH20IO::UNDEF::USHORT)
      |                    ^~~~~~~
src/esphome/components/intexsbh20/SBHClimate.cpp: In member function 'virtual void esphome::sbh20::SBHClimate::control(const esphome::climate::ClimateCall&)':
src/esphome/components/intexsbh20/SBHClimate.cpp:46:3: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   46 |   get_parent()->sbh()->setDesiredWaterTempCelsius(*tt);
      |   ^~~~~~~~~~
      |   get_name
src/esphome/components/intexsbh20/SBHClimate.cpp:52:3: error: 'get_parent' was not declared in this scope; did you mean 'get_name'?
   52 |   get_parent()->sbh()->setHeaterOn(*mode == climate::CLIMATE_MODE_HEAT);
      |   ^~~~~~~~~~
      |   get_name
src/esphome/components/intexsbh20/SBHClimate.cpp: In member function 'virtual esphome::climate::ClimateTraits esphome::sbh20::SBHClimate::traits()':
src/esphome/components/intexsbh20/SBHClimate.cpp:60:32: error: 'SBH20IO' has not been declared
   60 |  rv.set_visual_min_temperature(SBH20IO::WATER_TEMP::SET_MIN);
      |                                ^~~~~~~
src/esphome/components/intexsbh20/SBHClimate.cpp:61:32: error: 'SBH20IO' has not been declared
   61 |  rv.set_visual_max_temperature(SBH20IO::WATER_TEMP::SET_MAX);
      |                                ^~~~~~~
In file included from src/esphome/components/intexsbh20/intexsbh20.cpp:3:
src/esphome/components/intexsbh20/SBHClimate.h: At global scope:
src/esphome/components/intexsbh20/SBHClimate.h:9:95: error: 'IntexSBH20' is not a member of 'esphome::sbh20'
    9 | class SBHClimate : public esphome::climate::Climate, public esphome::Parented<esphome::sbh20::IntexSBH20>
      |                                                                                               ^~~~~~~~~~
src/esphome/components/intexsbh20/SBHClimate.h:9:105: error: template argument 1 is invalid
    9 | class SBHClimate : public esphome::climate::Climate, public esphome::Parented<esphome::sbh20::IntexSBH20>
      |                                                                                                         ^
src/esphome/components/intexsbh20/intexsbh20.cpp:8:6: error: 'IntexSBH20' has not been declared
    8 | void IntexSBH20::setup()
      |      ^~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp: In function 'void esphome::sbh20::setup()':
src/esphome/components/intexsbh20/intexsbh20.cpp:10:2: error: 'sbh_' was not declared in this scope
   10 |  sbh_.setup(LANG::EN);
      |  ^~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:10:13: error: 'LANG' has not been declared
   10 |  sbh_.setup(LANG::EN);
      |             ^~~~
src/esphome/components/intexsbh20/intexsbh20.cpp: At global scope:
src/esphome/components/intexsbh20/intexsbh20.cpp:13:6: error: 'IntexSBH20' has not been declared
   13 | void IntexSBH20::loop()
      |      ^~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp: In function 'void esphome::sbh20::loop()':
src/esphome/components/intexsbh20/intexsbh20.cpp:15:2: error: 'sbh_' was not declared in this scope
   15 |  sbh_.loop();
      |  ^~~~
src/esphome/components/intexsbh20/intexsbh20.cpp: At global scope:
src/esphome/components/intexsbh20/intexsbh20.cpp:18:6: error: 'IntexSBH20' has not been declared
   18 | void IntexSBH20::update()
      |      ^~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp: In function 'void esphome::sbh20::update()':
src/esphome/components/intexsbh20/intexsbh20.cpp:20:7: error: 'sbh_' was not declared in this scope
   20 |  if (!sbh_.isOnline())
      |       ^~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:22:3: error: 'status_set_error' was not declared in this scope
   22 |   status_set_error();
      |   ^~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:26:6: error: 'status_has_error' was not declared in this scope
   26 |  if (status_has_error())
      |      ^~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:27:3: error: 'status_clear_error' was not declared in this scope
   27 |   status_clear_error();
      |   ^~~~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:29:19: error: 'sbh_' was not declared in this scope
   29 |  int errorValue = sbh_.getErrorValue();
      |                   ^~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:32:3: error: 'status_set_warning' was not declared in this scope
   32 |   status_set_warning();
      |   ^~~~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:34:7: error: 'error_text_' was not declared in this scope; did you mean 'error_t'?
   34 |   if (error_text_)
      |       ^~~~~~~~~~~
      |       error_t
src/esphome/components/intexsbh20/intexsbh20.cpp:37:11: error: 'status_has_warning' was not declared in this scope
   37 |  else if (status_has_warning())
      |           ^~~~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:39:3: error: 'status_clear_warning' was not declared in this scope
   39 |   status_clear_warning();
      |   ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:41:7: error: 'error_text_' was not declared in this scope; did you mean 'error_t'?
   41 |   if (error_text_)
      |       ^~~~~~~~~~~
      |       error_t
src/esphome/components/intexsbh20/intexsbh20.cpp:45:6: error: 'switch_bubble_' was not declared in this scope
   45 |  if (switch_bubble_)
      |      ^~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:47:6: error: 'switch_filter_' was not declared in this scope
   47 |  if (switch_filter_)
      |      ^~~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:49:6: error: 'switch_power_' was not declared in this scope
   49 |  if (switch_power_)
      |      ^~~~~~~~~~~~~
src/esphome/components/intexsbh20/intexsbh20.cpp:52:6: error: 'climate_' was not declared in this scope; did you mean 'climate'?
   52 |  if (climate_)
      |      ^~~~~~~~
      |      climate
*** [/data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/SBHClimate.cpp.o] Error 1
*** [/data/esphome-web-819576/.pioenvs/esphome-web-819576/src/esphome/components/intexsbh20/intexsbh20.cpp.o] Error 1
========================== [FAILED] Took 9.74 seconds ==========================

**Comment by jnsbyr** [comment]
Can't help specifically as I do not have a ESPHome environment.

On first glance it looks like a Makefile/build related problem. It's always a good idea to start at the top:

> src/esphome/components/intexsbh20/SBH20IO.cpp:1:1: error: expected unqualified-id before '.' token
> 1 | ../../../SBH20IO.cpp
> | ^

I don't think that the 1st char on the first source line is the real problem here, as it should be "/*" (start of a comment) in SBH20IO.cpp. Looking closer you see the long relative path for the source file. As I don't have experience with ESPHome, I don't know if this is typical, but I would try to avoid this. What the error really seems to complain about is the "|". This is also not part of the source file, so it must be coming form somewhere else.

All other errors seem to have a similar pattern. So I suggest you check your build environment. Maybe there is someone who knows ESPHome who can offer more support.

**Comment by RianFlow** [comment]
ok. Da ich kompletter Neuling auf diesem Gebiet bin, frag ich mich ob ich irgendwas an diesen Dateien ändern muss. An sich sind die Dateien ja leer. Und im Internet finde ich nichts dazu wie man so ein etwas größeres Projekt richtig auf den ESP bekommt. LG


OK. Since I'm a complete novice in this area, I'm wondering if I need to change anything in these files. The files are actually empty. And I can't find anything on the internet about how to properly get such a larger project on the ESP. LG

**Comment by jnsbyr** [comment]
ESPHome is a platform of its own, in a way a competitor to Arduino. I assume that it might be possible to make the transition, but it could get hard, because the existing code uses interrupt service routines that must be kept in the RAM and not in the FLASH. These routines use almost all the RAM that is available on the ESP8266 so it might become difficult to make it work, if the platform itself also needs resources of that type. As the code is time critical even at 160 MHz, there is no alternative way to implement it without external hardware. Have a look at [diyscip](https://github.com/YorffoeG/diyscip) if you want to go that way.

If you hope that you might easily expand the current functionality with ESPHome, this might become difficult because of the same reason: The project needs almost all available RAM resources for its own purposes.

My advise: if you "just" want to make it work quickly, stay with Arduino firmware and do the interesting things like a web UI or remote control on the other side of the MQTT server with a smart home application.

**Comment by RianFlow** [comment]
Ich habe jetzt versucht das ganze über Arduino zumachen. Hat soweit auch gut geklappt. Nur im Home Assistant finde ich nur den Temperatur zustand und den Device tracker. Muss ich noch irgendwas umbennenen?

I've now tried to close the whole thing via Arduino. Has worked well so far. I can only find the temperature status and the device tracker in the Home Assistant. Do I need to rename anything?

**Comment by jnsbyr** [comment]
Wenn die Verbindung zwischen ESP und MQTT Server steht, solltest du in der Lage sein, alle vom ESP gemeldeten Topics zu empfangen (siehe [README/MQTT/Published Topics](https://github.com/jnsbyr/esp8266-intexsbh20#mqtt).

Vermutlich musst du jeden Topic einzeln mit einer Komponente im Home Assistent verknüpfen.

**Comment by jnsbyr** [comment]
closed due to inactivity
