### ISSUE TITLE
Sanitizer on SJB

### ISSUE THREAD

**Issue by Andromede88** [jnsbyr/esp8266-intexsbh20#3]
Hi,
I saw that you based on the work of Geoffroy, he managed to integrate the control of the sanitizer. 
Is this an option that your amazing system could integrate too ?

**Comment by jnsbyr** [comment]
I am not sure to what kind of setup you refer to. Please explain in more detail.

This project is based on some of the basic principles that Intex uses for the communication between the mainboard and the control panel of the spa that Geoffroy has documented. But it is not an extension (fork) of Geoffroy's project and it is geared to the SB-H20 model instead. Currently there is no explicit support for other models and the SB-H20 models I have seen so far do not have a sanitizer.

Did you try this project with an SJB model and did it work, maybe at least partly?
