### ISSUE TITLE
config file 'config.json' not found

### ISSUE THREAD

**Issue by MichelMazzola** [jnsbyr/esp8266-intexsbh20#39]
Hello,
I have finaly found how to load the json file. 

Thanks

**Comment by jnsbyr** [comment]
Thanks for your feedback.

**Comment by jnsbyr** [comment]
@MichelMazzola 

If you want to improve on the subject you should have a look at [PlatformIO Pre & Post Actions](https://docs.platformio.org/en/latest/scripting/actions.html#pre-post-actions).

It should be possible to copy the data folder from the src subfolder to the main folder if it is missing. Please post your solution here if you find a solution.
