### ISSUE TITLE
PCBs available

### ISSUE THREAD

**Issue by Vrumfondel** [jnsbyr/esp8266-intexsbh20#41]
Hello together:

to everyone who is interested: I just placed an order for some PCBs for this project. If someone is interested I can offer them for 3€ + Shipping.

**Comment by tortfeaser** [comment]
Hi there, if you have a PCB available still I'd like to buy one. Let me know how I can get some $ to you (Paypal?).

**Comment by Saarblick** [comment]
Hello,
I would like also an PCB when its still available!

Regards
Thomas

**Comment by Vrumfondel** [comment]
PCBs are still availabe. Please write me a personal message with the shipping address, then I can check for the shipment cost.

**Comment by Saarblick** [comment]
Done, hope you're mail adress are still valid

**Comment by Vrumfondel** [comment]
Sorry, it was not. Should be fixed now

**Comment by github-lx2020** [comment]
Hi,
Still one Board available?
Thank you

**Comment by Vrumfondel** [comment]
Yes

**Comment by jnsbyr** [comment]
closed due to inactivity
