### ISSUE TITLE
How to use a different mqtt Port

### ISSUE THREAD

**Issue by serb91** [jnsbyr/esp8266-intexsbh20#5]
Hi,

i am trying to use your Project on a Intex SimpleSpa
At first step i want to flash my d1 mini and also get it in iobroker. 
my problem is, that i have to use a different port for mqtt, for example 4321. 
In you project mqtt is using the standardport which is 1883. 
can you describe me how/where i have to change the mqtt-port in you project to use (for example) 4321?
Thanks a lot!

**Comment by serb91** [comment]
Please close it - i edit the MQTT-Port with Gitpod and now i can use your File with a different Port.
Your Manuel also work with my Intex Simple Spa (https://www.steinbach-group.com/de/128482-simple-spa-73976de/)
Thx alot!

**Comment by jnsbyr** [comment]
Glad you could help yourself and thanks for the compatibility info. I added it to the readme.

**Comment by serb91** [comment]
Thx for your mail
Can you maybe describe me how i can add a static IP?

I search online for an answer but i dont find one 😕

Thx!
Igor

Ps: if its better for you we can write in german 😊



Jens B. ***@***.***> schrieb am So. 12. Juni 2022 um 19:45:

**Comment by jnsbyr** [comment]
@serb91 
Your question regarding a static IP is a little of topic - but who cares. Assuming you want you WiFi client to use a static IP you must add a call to WiFi.config() before calling WiFi.begin() in the INO. Have a look at this [tutorial](https://techtutorialsx.com/2020/04/21/esp32-arduino-set-static-ip-address/) for the details. It is about an ESP32 but the Arduino code is the same.

**Comment by serb91** [comment]
Sry about off topic..
Thx a lot!
I will look at the tutorial this week

Jens B. ***@***.***> schrieb am So. 12. Juni 2022 um 20:47:
